### ISSUE TITLE
Docker image tags outdated

### ISSUE THREAD

**Issue by svenmueller** [google/cadvisor#1075]
Please update the docker tags `latest` and `beta` properly. Currently they are quite outdated.

``` bash
docker images
REPOSITORY                                 TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
google/cadvisor                            latest              a1c47b5aade9        3 months ago        22.78 MB
google/cadvisor                            beta                2a9248ff0e26        6 months ago        19.92 MB
```

**Comment by vishh** [comment]
I have fixed this manually for now. 
@pwittrock: can we extend the jenkins pusher to sync the `latest` tag to the most recent release?

**Comment by svenmueller** [comment]
just pulled the current `latest` tag. when running the container, the logs shows:

```bash
I0125 21:31:10.290451 00001 cadvisor.go:94] Starting cAdvisor version: "0.18.0" on port 8080
```

is that the latest stable version? when looking at the "releases" section, i expected version `0.20.1` (https://github.com/google/cadvisor/releases)

Thx,
Sven

**Comment by vishh** [comment]
Oops. Operator error. Can you check again?

**Comment by svenmueller** [comment]
Hi,

Still the same version for me (although a new iamge was pulled).

```bash
$ docker images
REPOSITORY                                 TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
google/cadvisor                            latest              3f6443d29d3e        11 minutes ago      35 MB
```

```bash
docker logs -f cadvisor
...
I0125 21:56:03.652602 00001 cadvisor.go:94] Starting cAdvisor version: "0.18.0" on port 8080
...
```

**Comment by vishh** [comment]
Err. Looks like the build/release scripts have changed. Apologies. Updated
again.
$ docker run --rm -it google/cadvisor:latest
...
I0125 22:10:48.852680       1 manager.go:254] Recovery completed
I0125 22:10:48.853630       1 cadvisor.go:106] Starting cAdvisor version:
0.20.1-634965a on port 8080
...

**Comment by pwittrock** [comment]
I looked into this a while back for labeling each release, and the plugin we use for the existing jenkins pusher didn't help much.  Might be possible to use the plugin for latest since it is a static label.  I plan to look into this after the k82 1.2 stuff dies down.

**Comment by ohmystack** [comment]
However, the tags `v0.20.4` & `0.19.3` are still packaged with a wrong version of cAdvisor bin, "0.18.0".

```
sudo docker run -it --rm --entrypoint='/bin/sh' google/cadvisor:v0.20.4
/ # cadvisor -version
cAdvisor version 0.18.0
```

```
sudo docker run -it --rm --entrypoint='/bin/sh' google/cadvisor:0.19.3
/ # cadvisor -version
cAdvisor version 0.18.0
```

**Comment by vishh** [comment]
I have updated `google/cadvisor:0.19.3` and verified that `google/cadvisor:v0.20.4` contains the right version.

**Comment by jimmidyson** [comment]
How about 0.20.5?

**Comment by vishh** [comment]
I pushed 0.20.5 as well.

**Comment by jimmidyson** [comment]
Thanks!

**Comment by dashpole** [comment]
closing since this issue is resolved.
