### ISSUE TITLE
Integration tests are failing on RHEL

### ISSUE THREAD

**Issue by vishh** [google/cadvisor#1130]
CI is failing on HEAD with the following error:

```
W0226 08:08:57.489940   10739 runner.go:173] Skipping retry for tests on host e2e-cadvisor-rhel-7 because error is not whitelisted
E0226 08:08:57.719065   10739 runner.go:189] ----------------------
Logs from Host: "e2e-cadvisor-rhel-7"
I0226 16:07:30.939003   17838 storagedriver.go:45] Caching stats in memory for 2m0s
I0226 16:07:30.939160   17838 manager.go:168] cAdvisor running in container: "/"
I0226 16:07:31.054803   17838 fs.go:109] Filesystem partitions: map[/dev/sda1:{mountpoint:/ major:8 minor:1 fsType: blockSize:0}]
I0226 16:07:31.064065   17838 manager.go:205] Machine: {NumCores:1 CpuFrequency:2499998 MemoryCapacity:3880640512 MachineID:335583a614774df61a1a3adafc81ddce SystemUUID:392B2C22-C865-3467-87A5-0755C799D501 BootID:93ffbeb6-5380-4c59-b2df-bdae1d5dab74 Filesystems:[{Device:/dev/sda1 Capacity:10724835328 Type:vfs Inodes:10483712}] DiskMap:map[253:0:{Name:dm-0 Major:253 Minor:0 Size:107374182400 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:10737418240 Scheduler:deadline}] NetworkDevices:[{Name:eth0 MacAddress:42:01:0a:f0:00:09 Speed:0 Mtu:1460}] Topology:[{Id:0 Memory:4026122240 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:31457280 Type:Unified Level:3}]}] CloudProvider:GCE InstanceType:n1-standard-1 InstanceID:4793473601241450566}
I0226 16:07:31.065391   17838 manager.go:211] Version: {KernelVersion:3.10.0-229.20.1.el7.x86_64 ContainerOsVersion:Red Hat Enterprise Linux Server 7.1 (Maipo) DockerVersion:1.9.1 CadvisorVersion: CadvisorRevision:}
I0226 16:07:31.171002   17838 factory.go:233] Registering Docker factory
I0226 16:07:31.171442   17838 factory.go:97] Registering Raw factory
I0226 16:07:31.275285   17838 manager.go:1039] Started watching for new ooms in manager
I0226 16:07:31.275785   17838 oomparser.go:198] OOM parser using kernel log file: "/var/log/messages"
I0226 16:07:31.276692   17838 manager.go:292] Starting recovery of all containers
I0226 16:07:31.314287   17838 manager.go:297] Recovery completed
I0226 16:07:31.338188   17838 cadvisor.go:106] Starting cAdvisor version: - on port 8080
E0226 16:08:35.144618   17838 fsHandler.go:106] failed to collect filesystem stats - du command failed on /var/lib/docker/containers/d3d4cef048b563492d6566b6b17ba078fcb4aa65d577192fe5e1b9b749d73739 with output stdout: , stderr: du: cannot access ‘/var/lib/docker/containers/d3d4cef048b563492d6566b6b17ba078fcb4aa65d577192fe5e1b9b749d73739’: No such file or directory
 - exit status 1

I0226 08:08:58.308632   10739 runner.go:198] Execution time 1m35.59396963s
F0226 08:08:58.308696   10739 runner.go:291] Error 0: error on host e2e-cadvisor-rhel-7: command "godep" ["go" "test" "--timeout" "15m0s" "" "github.com/google/cadvisor/integration/tests/..." "--host" "e2e-cadvisor-rhel-7" "--port" "8080" "--ssh-options" "-i /home/jenkins/.ssh/google_compute_engine -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no"] failed with error: exit status 1 and output: "?   \tgithub.com/google/cadvisor\t[no test files]\n--- FAIL: TestDockerFilesystemStats (7.40s)\n\tassertions.go:150: \r                        \r\tLocation:\tdocker_test.go:336\n\t\t\r\tError:\t\tExpected not to be nil.\n\t\t\r\tMessages:\tgot info: {Spec:{CreationTime:2016-02-26 16:08:50.302839811 +0000 UTC Aliases:[admiring_dubinsky e715d19b52429d08dd43a39cfb12d61b015ff2dda7db686636a3803f031eb76f] Namespace:docker Labels:map[] Envs:map[] HasCpu:true Cpu:{Limit:1024 MaxLimit:0 Mask:0 Quota:0 Period:0} HasMemory:true Memory:{Limit:18446744073709551615 Reservation:0 SwapLimit:18446744073709551615} HasCustomMetrics:false CustomMetrics:[] HasNetwork:true HasFilesystem:false HasDiskIo:true Image:busybox} Stats:[0xc20805aa80]}\n\t\t\r\nFAIL\nFAIL\tgithub.com/google/cadvisor/integration/tests/api\t83.364s\nok  \tgithub.com/google/cadvisor/integration/tests/healthz\t0.023s\ngodep: go exit status 1\n"
&{KernelVersion:3.10.0-229.20.1.el7.x86_64 ContainerOsVersion:Red Hat Enterprise Linux Server 7.1 (Maipo) DockerVersion:1.9.1 CadvisorVersion: NumCores:1 CpuFrequency:2499998 MemoryCapacity:3880640512 MachineID:335583a614774df61a1a3adafc81ddce SystemUUID:392B2C22-C865-3467-87A5-0755C799D501 Filesystems:[{Device:/dev/sda1 Capacity:10724835328 Type:vfs Inodes:10483712}] DiskMap:map[253:0:{Name:dm-0 Major:253 Minor:0 Size:107374182400 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:10737418240 Scheduler:deadline}] NetworkDevices:[{Name:eth0 MacAddress:42:01:0a:f0:00:09 Speed:0 Mtu:1460}] Topology:[{Id:0 Memory:4026122240 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:31457280 Type:Unified Level:3}]}] CloudProvider:GCE InstanceType:n1-standard-1}
Build step 'Execute shell' marked build as failure
```

**Comment by vishh** [comment]
cc @ncdc

**Comment by ncdc** [comment]
cc @sjenning

**Comment by sjenning** [comment]
After hacking the test code to prevent removal of the containers after use:

```
# build/integration.sh
>> starting cAdvisor locally
>> running integration tests against local cAdvisor
--- FAIL: TestAttributeInformationIsReturned (0.00s)
	attributes_test.go:31: unable to post "attributes" to "http://localhost:8080/api/v2.1/attributes": Get http://localhost:8080/api/v2.1/attributes: dial tcp 127.0.0.1:8080: connection refused
--- FAIL: TestDockerFilesystemStats (0.91s)
        Location:       docker_test.go:336
	Error:		Expected not to be nil.
	Messages:	got info: {Spec:{CreationTime:2016-02-26 22:54:37.618844915 +0000 UTC Aliases:[distracted_mayer 9e09afa35ffd33a79a51cd4f235f04f65345b5b14f38e889c463a9d384356792] Namespace:docker Labels:map[] Envs:map[] HasCpu:true Cpu:{Limit:1024 MaxLimit:0 Mask:0-3 Quota:0 Period:0} HasMemory:true Memory:{Limit:18446744073709551615 Reservation:0 SwapLimit:18446744073709551615} HasCustomMetrics:false CustomMetrics:[] HasNetwork:true HasFilesystem:false HasDiskIo:true Image:busybox} Stats:[0xc20804f3e0]}
		
FAIL
FAIL	github.com/google/cadvisor/integration/tests/api	47.968s
--- FAIL: TestHealthzOk (0.00s)
	healthz_test.go:32: Get http://localhost:8080/healthz: dial tcp 127.0.0.1:8080: connection refused
FAIL
FAIL	github.com/google/cadvisor/integration/tests/healthz	0.012s
godep: go exit status 1
Integration tests failed
>> stopping cAdvisor

# docker logs distracted_mayer
/bin/sh: dd if=/dev/zero of=/file count=2 bs=8 & sleep 10000: not found
```

It appears to be treating the entire string as a single command.  Fixed with this:

```
index 8d30edf..52f563b 100644
--- a/integration/tests/api/docker_test.go
+++ b/integration/tests/api/docker_test.go
@@ -300,7 +300,7 @@ func TestDockerFilesystemStats(t *testing.T) {
                sleepDuration = 10 * time.Second
        )
        // Wait for the container to show up.
-       containerId := fm.Docker().RunBusybox("/bin/sh", "-c", fmt.Sprintf("'dd if=/dev/zero of=/file count=2 bs=%d & sleep 1
+       containerId := fm.Docker().RunBusybox("/bin/sh", "-c", fmt.Sprintf("\"dd if=/dev/zero of=/file count=2 bs=%d & sleep 
        waitForContainer(containerId, fm)
        request := &v2.RequestOptions{
                IdType: v2.TypeDocker,
```

but then fell through to a bunch more errors

```
# build/integration.sh
>> starting cAdvisor locally
>> running integration tests against local cAdvisor
--- FAIL: TestAttributeInformationIsReturned (0.00s)
	attributes_test.go:31: unable to post "attributes" to "http://localhost:8080/api/v2.1/attributes": Get http://localhost:8080/api/v2.1/attributes: dial tcp 127.0.0.1:8080: connection refused
--- FAIL: TestDockerFilesystemStats (100.94s)
	docker_test.go:320: stats unavailable - request "http://localhost:8080/api/v2.1/stats/e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a?count=1&recursive=false&type=docker" failed with error: "unable to find Docker container \"e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a\""
	docker_test.go:321: retrying after 10s...
	docker_test.go:320: stats unavailable - request "http://localhost:8080/api/v2.1/stats/e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a?count=1&recursive=false&type=docker" failed with error: "unable to find Docker container \"e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a\""
	docker_test.go:321: retrying after 10s...
	docker_test.go:320: stats unavailable - request "http://localhost:8080/api/v2.1/stats/e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a?count=1&recursive=false&type=docker" failed with error: "unable to find Docker container \"e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a\""
	docker_test.go:321: retrying after 10s...
	docker_test.go:320: stats unavailable - request "http://localhost:8080/api/v2.1/stats/e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a?count=1&recursive=false&type=docker" failed with error: "unable to find Docker container \"e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a\""
	docker_test.go:321: retrying after 10s...
	docker_test.go:320: stats unavailable - request "http://localhost:8080/api/v2.1/stats/e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a?count=1&recursive=false&type=docker" failed with error: "unable to find Docker container \"e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a\""
	docker_test.go:321: retrying after 10s...
	docker_test.go:320: stats unavailable - request "http://localhost:8080/api/v2.1/stats/e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a?count=1&recursive=false&type=docker" failed with error: "unable to find Docker container \"e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a\""
	docker_test.go:321: retrying after 10s...
	docker_test.go:320: stats unavailable - request "http://localhost:8080/api/v2.1/stats/e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a?count=1&recursive=false&type=docker" failed with error: "unable to find Docker container \"e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a\""
	docker_test.go:321: retrying after 10s...
	docker_test.go:320: stats unavailable - request "http://localhost:8080/api/v2.1/stats/e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a?count=1&recursive=false&type=docker" failed with error: "unable to find Docker container \"e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a\""
	docker_test.go:321: retrying after 10s...
	docker_test.go:320: stats unavailable - request "http://localhost:8080/api/v2.1/stats/e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a?count=1&recursive=false&type=docker" failed with error: "unable to find Docker container \"e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a\""
	docker_test.go:321: retrying after 10s...
	docker_test.go:320: stats unavailable - request "http://localhost:8080/api/v2.1/stats/e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a?count=1&recursive=false&type=docker" failed with error: "unable to find Docker container \"e6183f199554d7f044d0270bc382a175d87920746d2efe100ace057a1042275a\""
	docker_test.go:321: retrying after 10s...
FAIL
FAIL	github.com/google/cadvisor/integration/tests/api	148.282s
--- FAIL: TestHealthzOk (0.00s)
	healthz_test.go:32: Get http://localhost:8080/healthz: dial tcp 127.0.0.1:8080: connection refused
FAIL
FAIL	github.com/google/cadvisor/integration/tests/healthz	0.005s
godep: go exit status 1
Integration tests failed
>> stopping cAdvisor
```

Still looking...

Also cadvisor doesn't build on RHEL7 without some changes to ```build/build.sh```

**Comment by vishh** [comment]
@ncdc mentioned that RHEL7 doesn't support go 1.5 yet. We can fix the build scripts to make builds just work on RHEL. 
The error after the fix still seems to indicate some issues with running the test container.

**Comment by sjenning** [comment]
There are a number of issues on RHEL7 so I'll just take them one by one, opening issues and PRs for each.

**Comment by sjenning** [comment]
#1136 fixes the "du: not found" issue caused by early termination of the container due to bad start command syntax

#1135 is the remaining issue caused by lack of filesystem stats support for containers using devicemapper

**Comment by vishh** [comment]
@sjenning: #1144 fixes the ssh issues (hopefully). But the CI is still failing on RHEL alone.

**Comment by sjenning** [comment]
@vishh I assume the test case that is failing is the TestDockerFilesystemStats and would be resolved by #1143?

**Comment by sjenning** [comment]
This is "fixed" by #1143.  I'll open a new issue to track re-enabling this test for RHEL.

**Comment by dashpole** [comment]
closed via #1143
